# Generated by Django 3.1.12 on 2021-06-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='VideoTape Title')),
                ('slug', models.SlugField(editable=False, max_length=256, unique=True)),
                ('description', models.TextField(verbose_name='VideoTape Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
