# Generated by Django 3.1.12 on 2021-06-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoRental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotape',
            name='genres',
            field=models.TextField(null=True, verbose_name='VideoTape Genres'),
        ),
    ]
